name: logmein-host
version: '1.2.0'
summary: The LogMeIn Host Software (Beta) for Linux # 79 char long summary
icon: snap/gui/icon.png
base: core18
description: |-
 LogMeIn allows you to access your computers from any device.

 You can connect to a Linux host, in an web-based secure shell and it allows you to send commands to the host computer.

 For more information on LogMeIn for Linux and how to attach your host to your account, try the developer website.

 Other contributions:
 - Added the prompt to ask for ssh port when terminal is requested. Edited by Jerry
 - Bump the nodejs version to 16.19.1 (LTS). Edited by Jerry

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  pytty:
    plugin: python
    source: .
    requirements: [ requirements.txt ]
    stage-packages: [ openssh-client ]
  reverse-proxy:
    source: reverse-proxy/
    plugin: nodejs
    nodejs-version: 16.19.1
    nodejs-package-manager: yarn
    build-environment:
      - npm_config_unsafe_perm: 'true'
      - npm_config_prefer_online: 'true'
    build-packages: [ git, gcc, g++, make, python, build-essential ]

apps:
  pytty:
    command: pytty
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  wetty:
    command: wetty --port 23822 --title LogMeIn --base /xterm/ --host 127.0.0.1 --forcessh
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  logmein-host:
    command: logmein_host
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control ]
  reverse-proxy:
    command: reverse-proxy
    daemon: simple
    restart-condition: always
    plugs: [ network, network-bind, process-control, hostname-control ]
